development:
  adapter: postgresql
  database: new999
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: new999
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: new999
  pool: 5
  timeout: 5000